apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-hedge-fund-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-hedge-fund-clone
  template:
    metadata:
      labels:
        app: ai-hedge-fund-clone
    spec:
      containers:
      - name: ai-hedge-fund-clone
        image: your-dockerhub-username/ai-hedge-fund-clone:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-hedge-fund-clone-service
spec:
  type: LoadBalancer
  selector:
    app: ai-hedge-fund-clone
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
